# Generated by Django 3.1.4 on 2021-01-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hmj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ketua', models.CharField(max_length=50)),
                ('gambar_ketua', models.ImageField(blank=True, null=True, upload_to='')),
                ('motto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Presma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ketua', models.CharField(max_length=50)),
                ('nama_wakil', models.CharField(max_length=50)),
                ('gambar_ketua', models.ImageField(blank=True, null=True, upload_to='')),
                ('gambar_wakil', models.ImageField(blank=True, null=True, upload_to='')),
                ('motto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('kode_prodi', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nama_prodi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('npm', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('tingkat', models.CharField(max_length=5)),
                ('kelas', models.CharField(max_length=10)),
                ('headphone', models.CharField(max_length=20)),
                ('aktivasi', models.BooleanField(default=False)),
                ('prodi_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPUapp.prodi')),
            ],
        ),
        migrations.CreateModel(
            name='Suara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id_Hmj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPUapp.hmj')),
                ('id_presma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPUapp.presma')),
                ('npm_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPUapp.users')),
            ],
        ),
        migrations.AddField(
            model_name='hmj',
            name='prodi_hmj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPUapp.prodi'),
        ),
    ]
