# Generated by Django 3.1.4 on 2021-01-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hmj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ketua', models.CharField(max_length=50)),
                ('motto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Presma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ketua', models.CharField(max_length=50)),
                ('nama_wakil', models.CharField(max_length=50)),
                ('motto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('kode_prodi', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_prodi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('npm', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('prodi_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.prodi')),
            ],
        ),
        migrations.CreateModel(
            name='Suara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_Hmj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hmj')),
                ('id_presma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.presma')),
                ('npm_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.AddField(
            model_name='hmj',
            name='prodi_hmj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.prodi'),
        ),
    ]
